### ISSUE TITLE
`forest_minimize` slows down with n_jobs=4

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#181] opened 2016-08-02 23:02 UTC
Curious thing I noticed today:

``` python
%%time
bounds = [(0., 1.),] * 8
n_calls = 200

res = forest_minimize(hart6, bounds, n_calls=n_calls,
                             base_estimator="et", random_state=4)
# CPU times: user 26.5 s, sys: 267 ms, total: 26.8 s
# Wall time: 26.8 s

%%time
bounds = [(0., 1.),] * 8
n_calls = 200

res = forest_minimize(hart6, bounds, n_calls=n_calls, n_jobs=4,
                             base_estimator="et", random_state=4)
# CPU times: user 34.1 s, sys: 2.71 s, total: 36.8 s
# Wall time: 1min 2s
```

Not quite sure what the ratio of CPU, user and wall time is trying to tell us. For sure it is unexpected that it would take longer in real time with more jobs.

**Comment by MechCoder** [comment] 2016-08-27 19:14
This should be reported upstream to sklearn (and maybe joblib), I suppose. There is nothing we can do above it right?

**Comment by MechCoder** [comment] 2016-08-27 19:22
It might be because initially, the number of samples fit on each tree in parallel is very less, so the joblib overhead is not worth fitting it in parallel..

Should we add a note?

**Comment by MechCoder** [comment] 2016-08-31 22:35
Also worth noting that in my initial benchmarks,  I faced the same "issue" (https://github.com/scikit-learn/scikit-learn/pull/5491#issuecomment-185459918)

Maybe we can fall back to `n_jobs=1` when `n_calls` (here the number of samples) is pretty less and as the number of calls increases we can set `n_jobs=-1`?

**Comment by glouppe** [comment] 2017-12-29 14:32
Is this still an issue with the latest scikit-learn?

**Comment by iaroslav-ai** [comment] 2018-01-22 23:51
Both approaches take the same time now on my machine (35.5 vs 35.2 seconds), reproduce with this:
```python
from time import time
from skopt import forest_minimize
from skopt.benchmarks import hart6

bounds = [(0., 1.),] * 6
n_calls = 200

s = time()
res = forest_minimize(hart6, bounds, n_calls=n_calls, random_state=4)
print(time()-s)

bounds = [(0., 1.),] * 6
n_calls = 200

s = time()
res = forest_minimize(hart6, bounds, n_calls=n_calls, n_jobs=4, random_state=4)
print(time()-s)
```
Not sure what we can do. Close this for now - feel free to reopen again.

**Closed** 2018-01-22 23:52 UTC
Labels: Bug
