### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

### ISSUE THREAD

**Issue by pavelkomarov** [scikit-optimize/scikit-optimize#617] opened 2018-01-25 16:41 UTC
I'm really getting a lot of mileage out of this example:

```python
from skopt import Optimizer
    from skopt.utils import dimensions_aslist
    from skopt.space import Integer, Categorical, Real

    PPR = {
        'r': Integer(5,20),
        'epsStage': Real(0.01, 0.01, prior=log-uniform)
    }

    listified_space = dimensions_aslist(PPR)
    acq_optimizer_kwargs = {'n_points': 20, 'n_restarts_optimizer': 5, 'n_jobs': 3}
    acq_func_kwargs = {'xi': 0.01, 'kappa': 1.96}

    optimizer = Optimizer(listified_space, base_estimator='gp', n_initial_points=10,
        acq_func='EI', acq_optimizer='auto', random_state=None,
        acq_optimizer_kwargs=acq_optimizer_kwargs, acq_func_kwargs=acq_fun_kwargs)

    rand_xs = []
    for n in range(10):
        rand_xs.append(optimizer.ask())

    rand_ys = [1,2,3,4,5,6,7,8,9,10]

    print rand_xs
    print rand_ys

    optimizer.tell(rand_xs, rand_ys)
```

The above does not work because the Real parameter has the same upper and lower bound. I was doing this to keep it clamped to the one value, but it turns out that when the Optimizer transforms points from this space during `.tell()` it transforms to something full of `NaN`s in the Real dimension, presumably because it is normalizing by high-low=0 at some point.

This case should be explicitly not allowed via an error so others aren't as confused as I was.

**Comment by bstemper** [comment] 2018-01-31 14:56
I believe this is a duplicate of my issue #594 .

**Comment by pavelkomarov** [comment] 2018-01-31 15:21
I believe it is. @betatim, which one would you rather keep open? How can this be fixed in the code so we can fix it and close both?

**Comment by iaroslav-ai** [comment] 2018-03-23 20:33
Hi @pavelkomarov ,
thanks for reporting this!

I removed some undefined variables from the code, if you think this might have been important let me know:
```python
from skopt import Optimizer
from skopt.utils import dimensions_aslist
from skopt.space import Integer, Categorical, Real

PPR = {
    'r': Integer(5,20),
    'epsStage': Real(0.01, 0.01, prior="log-uniform")
}

listified_space = dimensions_aslist(PPR)
acq_optimizer_kwargs = {'n_points': 20, 'n_restarts_optimizer': 5, 'n_jobs': 3}
acq_func_kwargs = {'xi': 0.01, 'kappa': 1.96}

optimizer = Optimizer(listified_space, base_estimator='gp', n_initial_points=10,
    acq_func='EI', acq_optimizer='auto', random_state=None,
    acq_optimizer_kwargs=acq_optimizer_kwargs)

rand_xs = []
for n in range(10):
    rand_xs.append(optimizer.ask())

rand_ys = [1,2,3,4,5,6,7,8,9,10]

print rand_xs
print rand_ys

optimizer.tell(rand_xs, rand_ys)
```
With 0.4, I reproduce your error. With 0.5, I get 

```
ValueError: the lower bound 0.01 has to be less than the upper bound 0.01
````

So this is resolved.

In order to fix a dimension value, I usually use `Categorical` dimension with a single value:

```python
Categorical([0.01])
```

**Closed by iaroslav-ai** 2018-03-23 20:33 UTC
