### ISSUE TITLE
Diagnostic plots 📈📊📉

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#96] opened 2016-07-13 09:40 UTC
We should add some convenience functions that make plots similar to what is in the examples for "generic" problems to help people debug why things aren't converging or why they are converging to the value they are etc etc.

Maybe use something in the style of https://github.com/dfm/corner.py to show N>2 spaces, where the samples are, what the acquisition function looks like, ...

**Comment by glouppe** [comment] 2016-07-13 09:52
Duplicate of #67?

**Comment by betatim** [comment] 2016-07-13 10:19
Yes

**Closed** 2016-07-13 10:19 UTC
Labels: Enhancement, New feature
