### ISSUE TITLE
Updated benchmarks in separate repository?

### ISSUE THREAD

**Issue by iaroslav-ai** [scikit-optimize/scikit-optimize#439] opened 2017-07-17 08:24 UTC
I propose to create a separate repository eg scikit-optimize/benchmarks for benchmarking. This would allow:

1. Have dependencies not included in skopt
2. Keep data (eg datasets) necessary for benchmarks in the repo itself to not rely on online resources too much
3. As per 1., we could have dependencies and code for comparison with other optimization software. 

Would that be ok with everyone? I can create such repository, and I have an initial version of it already in my private repositories.
The issue of benchmarking is popping up in many issues when decision for A or B is necessary to make, and also in comments of people for the repository so far. Thus I think advancing in this direction is beneficial.

**Comment by betatim** [comment] 2017-07-17 10:08
Only downside I can think of is that a new repository means more "infrastructure" that needs keeping alive. It might sound trivial but having `setup.py` and travis and dependencies and wheels and docs and ... all work nicely is a fair amount of boring grunt work. It is totally manageable and splitting off has the benefits you listed so I just wanted to be the boring old guy pointing out that there is no free lunch :)

So if someone wants to be the janitor (maybe we give it a more appealing name) of the benchmarks repository then we should do it.

**Comment by iaroslav-ai** [comment] 2017-07-17 11:56
@betatim I think these are some good points that you are making and I would rather go with your experience on this. We could have a separate repository for data storage only if there will be a necessity, which requires (almost) no maintenance. Now that I think about it it is indeed better to increase least the amount of infrastructure maintained.

**Comment by iaroslav-ai** [comment] 2017-07-17 13:51
On a related note: we might want to offload the benchmarks to something like [http://www.coseal.net/aslib/](http://www.coseal.net/aslib/)

**Comment by betatim** [comment] 2017-07-17 15:31
For me it isn't clear whether splitting or not is the best option, just wanted to list some of the boring, tedious downsides :)

**Comment by MechCoder** [comment] 2017-07-18 05:53
We'll have to maintain the code irrespective of which repository it is in.

But +1 to move it separately because of a couple of reasons:

1. Use more dependencies to run advanced benchmarks.
2. Remove code that is unnecessary for scikit-optimize to run.

To address @betatim concerns, we need not make it a python package but just a bunch of scripts that are reproducible.

**Comment by iaroslav-ai** [comment] 2017-07-25 10:46
Thanks for the feedback. Lets move when the need arises to separate repository for data storage or complete code if necessary. For now I think it can do without moving. We can add requirements.txt to the benchmarks folder for extra dependencies.

**Comment by betatim** [comment] 2017-07-27 04:55
Sounds good. Closing this up then.

**Closed by betatim** 2017-07-27 04:55 UTC

**Comment by betatim** [comment] 2017-07-27 11:46
Not sure where to put this, so dropping it here:

http://pytest-benchmark.readthedocs.io/en/latest/

Looks really nice, especially the fact it can create plots for us. Might be something to investigate for some of the benchmarks that fit into a "test" or some of our "tests" which are actually more like a benchmark.

**Comment by iaroslav-ai** [comment] 2017-07-28 08:27
Oh, nice finding @betatim ! Seems interesting.

**Comment by iaroslav-ai** [comment] 2017-07-28 08:46
Seems good for execution speed performance testing
