### ISSUE TITLE
Using GaussianProcessRegressor fails for default values

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#308] opened 2017-02-01 23:04 UTC
```python
from skopt.learning import GaussianProcessRegressor

dimensions = [(-5.0, 10.0), (0.0, 15.0)]
gpr = GaussianProcessRegressor()
optimizer = Optimizer(
    dimensions=dimensions,
    base_estimator=gpr,
    n_random_starts=1,
    acq_func="EI",
    random_state=0)

optimizer.tell(optimizer.ask(), branin(x_cand))

AttributeError: 'Product' object has no attribute 'gradient_x'
```

**Comment by MechCoder** [comment] 2017-02-02 00:04
The problem is that by default sklearn's kernel is used and hence there is no `gradient_x` method.

**Comment by fredcallaway** [comment] 2017-06-30 18:39
This fix is still not on pip, as far as I can tell.

**Comment by betatim** [comment] 2017-07-03 11:48
Could you elaborate a bit? Tried to reproduce the error locally but can't. Checked out master and ran the `parallel-optimization.ipynb` notebook.

**Comment by fredcallaway** [comment] 2017-07-03 18:11
OK. I think the problem is that the version number has not changed between the PyPI version and the git version. When I pip installed from Github, I guess it didn't actually change anything because it saw that the version number was the same (0.3). 

I created a virtual env, installed from pip, recreated the `n_points` argument error, uninstalled, installed from github, and now it works.

**Comment by betatim** [comment] 2017-07-03 19:43
Thanks for the praise and for taking the time to track this down! I'll close this again. Not sure what the standard practice is for increasing the version number on master?

**Closed by betatim** 2017-07-03 19:43 UTC
Labels: Bug, Easy

**Comment by fredcallaway** [comment] 2017-07-03 21:54
http://semver.org/ suggests a version number like 0.3.1 where you increment the final digit for bug patches, the second for backward-compatible new functionality, and the first for backward-incompatible API changes.

**Comment by betatim** [comment] 2017-07-04 09:59
Nods, the question was whether we already bump the version in master before we make the next release or not.

**Comment by fredcallaway** [comment] 2017-07-04 17:16
Oh, I'm not sure then. My intuition says to increase the version number on master, if for no other reason than to avoid the situation I ran into. I think it would even be okay to have multiple patches on master between releases, such that 0.3.4 is the release after 0.3.2.

**Comment by betatim** [comment] 2017-07-04 19:39
Sounds good to me. Do you want to make a PR to bump the version up? If any of the others object they can do so in the PR :)

**Comment by mahdiabdollahpour** [comment] 2023-11-26 19:57
I still get the same error when using sci-kit learn RBF for sci-kit optimize gp_minimize, any idea how to solve it?

here is the code to reproduce it 

```
from numpy import mean
from pandas import read_csv
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.svm import SVC
from skopt.space import Integer
from skopt.space import Real
from skopt.space import Categorical
from skopt.utils import use_named_args
from skopt import gp_minimize
from skopt import gp_minimize, dummy_minimize
from sklearn.gaussian_process.kernels import RBF


import time
import numpy as np
from skopt.learning import GaussianProcessRegressor
from skopt.learning.gaussian_process.kernels import Matern

# define the space of hyperparameters to search
search_space = list()
# search_space.append(Real(1e-6, 100.0, 'log-uniform', name='C'))
# search_space.append(Categorical(['linear', 'poly', 'rbf', 'sigmoid'], name='kernel'))
# search_space.append(Integer(1, 5, name='degree'))
search_space.append(Real(1e-6, 100.0, 'log-uniform', name='gamma'))

other_kernel = RBF(length_scale=1.0)
base_estimator = GaussianProcessRegressor(
    kernel= other_kernel,
    normalize_y=True, noise="gaussian",
    n_restarts_optimizer=0)

# define the function used to evaluate a given configuration
@use_named_args(search_space)
def evaluate_model(**params):

    return 0.7


# load dataset
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/ionosphere.csv'
dataframe = read_csv(url, header=None)
# split into input and output elements
data = dataframe.values
X, y = data[:, :-1], data[:, -1]
print(X.shape, y.shape)
# perform optimization
result = gp_minimize(evaluate_model, search_space,base_estimator=base_estimator)
# summarizing finding:
print('Best Accuracy: %.3f' % (1.0 - result.fun))
print('Best Parameters: %s' % (result.x))
```


The error log
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-795400b0eace>](https://localhost:8080/#) in <cell line: 48>()
     46 print(X.shape, y.shape)
     47 # perform optimization
---> 48 result = gp_minimize(evaluate_model, search_space,base_estimator=base_estimator)
     49 # summarizing finding:
     50 print('Best Accuracy: %.3f' % (1.0 - result.fun))

18 frames
[/usr/local/lib/python3.10/dist-packages/skopt/learning/gaussian_process/gpr.py](https://localhost:8080/#) in predict(self, X, return_std, return_cov, return_mean_grad, return_std_grad)
    344 
    345             if return_mean_grad:
--> 346                 grad = self.kernel_.gradient_x(X[0], self.X_train_)
    347                 grad_mean = np.dot(grad.T, self.alpha_)
    348                 # undo normalisation

AttributeError: 'Sum' object has no attribute 'gradient_x'
```






package versions
```
scikit-learn==1.2.2
scikit-optimize==0.9.0
```
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
