### ISSUE TITLE
How to define parameter in grid which can be None?

### ISSUE THREAD

**Issue by christianblust** [scikit-optimize/scikit-optimize#659] opened 2018-04-17 14:36 UTC
Hi, 

I'm trying optimize hyperparameters for a `RandomForestClassifier `using `BayesSearchCV`:

```
params = {"min_samples_leaf": np.arange(1,30,2),
              "min_samples_split": np.arange(2,20,2),
              "max_depth": np.arange(2, 20, 2),
              "min_weight_fraction_leaf": np.arange(0. ,0.4, 0.1),
              "n_estimators": np.arange(10, 1000, 100),
              "max_features" : ['auto', 'sqrt', 'log2', None],
              "criterion" : ['entropy', 'gini']}
```

criterion works fine, however max_features is resulting in an error: 
`ValueError: could not convert string to float: 'log2'`

Should I compute the values by myself or is there some kind of workaround? I tried using Categorical from `skopt.space`

**Comment by betatim** [comment] 2018-04-17 17:10
I think the problem is that the `max_features` dimension isn't recognised as a `Categorical` from the values you gave. To work around try `"max_features" : skopt.space.Categorical(['auto', 'sqrt', 'log2', None])` which will explicitly make a categorical dimension.

This is a bug I would say, so if you have a moment to make a PR that would be great.

**Comment by christianblust** [comment] 2018-04-17 17:26
> To work around try "max_features" : skopt.space.Categorical(['auto', 'sqrt', 'log2', None]) which will explicitly make a categorical dimension.

Unfortunately I tried this already but it resulted in the same error. , I could define `n_features `in the beginning and calculate `sqrt `and `log2 ` to use floats instead of categories.

**Comment by christianblust** [comment] 2018-04-18 07:31
Sorry I'm relatively new to github, by PL you mean Pull Request? I thought you want me to report the bug?

**Comment by betatim** [comment] 2018-04-18 15:15
Indeed PR = Pull Request. Sorry for the jargon.

I will have to take a moment to think about how to fix this unfortunately :-/ If you know how to please do create a pull request. I'll post here again if I find out something.

**Comment by betatim** [comment] 2018-04-18 15:27
Could you post a more complete traceback of your error?

**Comment by christianblust** [comment] 2018-04-18 16:33
Sure: 
```
Traceback (most recent call last):
  File "C:/Users/chris/PycharmProjects/FormationDetection/TestHyperOpt.py", line 86, in <module>
    bs.fit(x_train, y_train)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\searchcv.py", line 654, in fit
    groups=groups, n_points=n_points_adjusted
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\searchcv.py", line 541, in _step
    params = optimizer.ask(n_points=n_points)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\optimizer\optimizer.py", line 372, in ask
    opt._tell(x, y_lie)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\optimizer\optimizer.py", line 486, in _tell
    est.fit(self.space.transform(self.Xi), self.yi)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\learning\gaussian_process\gpr.py", line 195, in fit
    super(GaussianProcessRegressor, self).fit(X, y)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\sklearn\gaussian_process\gpr.py", line 181, in fit
    X, y = check_X_y(X, y, multi_output=True, y_numeric=True)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\sklearn\utils\validation.py", line 573, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\sklearn\utils\validation.py", line 433, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
ValueError: could not convert string to float: 'auto'
```

**Comment by betatim** [comment] 2018-04-18 17:12
Thanks! And I think the fix for this is in #616 which has been sitting there for a while. Just refreshed it.

**Comment by christianblust** [comment] 2018-04-18 18:01
Thanks for the tip. I added the line `space = Space(normalize_dimensions(space.dimensions))` in the `utils.py` file in my `venv `folder. Unfortunately it still results in the "same" error:
```
Traceback (most recent call last):
  File "C:/Users/chris/PycharmProjects/FormationDetection/TestHyperOpt.py", line 87, in <module>
    bs.fit(x_train, y_train)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\searchcv.py", line 654, in fit
    groups=groups, n_points=n_points_adjusted
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\searchcv.py", line 541, in _step
    params = optimizer.ask(n_points=n_points)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\optimizer\optimizer.py", line 372, in ask
    opt._tell(x, y_lie)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\optimizer\optimizer.py", line 486, in _tell
    est.fit(self.space.transform(self.Xi), self.yi)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\learning\gaussian_process\gpr.py", line 195, in fit
    super(GaussianProcessRegressor, self).fit(X, y)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\sklearn\gaussian_process\gpr.py", line 181, in fit
    X, y = check_X_y(X, y, multi_output=True, y_numeric=True)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\sklearn\utils\validation.py", line 573, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\sklearn\utils\validation.py", line 433, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
ValueError: could not convert string to float: 'log2'
```

I tried it without None (no string) -> other error:
```
Traceback (most recent call last):
  File "C:/Users/chris/PycharmProjects/FormationDetection/TestHyperOpt.py", line 87, in <module>
    bs.fit(x_train, y_train)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\searchcv.py", line 654, in fit
    groups=groups, n_points=n_points_adjusted
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\searchcv.py", line 541, in _step
    params = optimizer.ask(n_points=n_points)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\optimizer\optimizer.py", line 350, in ask
    x = opt.ask()
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\optimizer\optimizer.py", line 322, in ask
    return self._ask()
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\optimizer\optimizer.py", line 397, in _ask
    for xi in self.Xi])
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\optimizer\optimizer.py", line 397, in <listcomp>
    for xi in self.Xi])
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\space\space.py", line 733, in distance
    distance += dim.distance(a, b)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\space\space.py", line 504, in distance
    " the space, not {} and {}.".format(a, b))
RuntimeError: Can only compute distance for values within the space, not 18 and 4.
```

**Comment by betatim** [comment] 2018-04-19 12:10
#616 got merged, could you confirm if this fixes your problem and if yes close this issue?

**Closed** 2018-05-22 17:20 UTC
