### ISSUE TITLE
Repeating discrete (integer/categorical) entries

### ISSUE THREAD

**Issue by ardunn** [scikit-optimize/scikit-optimize#163] opened 2016-07-28 18:33 UTC
Does anyone here have a workaround for repeated integer/categorical entries? For example, if I am searching the space 
`dimensions = [(1,10), (1,10),["red","green","blue"]]`
With a local optimum of:
`my_input = [1,1,"red"]`
Skopt will keep testing the same entries at or around this optimum. If anyone knows a way around these repeated calculations, it would be much appreciated!

**Comment by MechCoder** [comment] 2016-07-28 18:47
Hi,

Typically `gp_minimize` should not get stuck in a local minima because values far away from the local minima should have a high variance, hence one of these values with high exploration should be picked.

Could you try setting `n_restarts_optimizer` to something higher along with `search='lbfgs'` and let us know if the problem persists?

Also, is it possible to let us know the function that you are trying to optimize?

Thanks!

**Comment by ardunn** [comment] 2016-07-28 19:00
Sure, I will try that and get back to you.

The function I am trying to optimize is not visible to Skopt (I removed the need for a function call by just passing the input and output of a black-box function to Skopt instead) but the search space is basically of the form I was describing above: Two integer dimensions and a categorical dimension. The integer dimensions are both 52 integers and the categorical dimension is 7 categories, giving a total of 18,928 possible combinations. 

I am running into a repeat issue within 200-300 iterations, which is surprising because the highest scorers of my function are well spread throughout the entire space, and Skopt has not exhaustively found all high scorers.

**Comment by ardunn** [comment] 2016-07-28 19:40
For what I am doing I needed to modify the skopt file to move the optimization loop outside skopt since each function evaluation is highly expensive. I reassigned `yi` to `my_input`, `Xi` to `my_output` and made `gp_minimize` return `next_x` instead of `res` - everything else is default skopt. 

A simplified version of my problem is this. 

```
dim = [(1,10),(2,20),("red","blue","green","orange")]
my_input = [[9, 2,"green"]]
my_output = [12]

def BBfun (x):
    "highest score is 10, 20, red"
    score = 0
    score+= x[0]*x[1]
    if x[2] == "red":
        score+=10
    elif x[2]=="orange":
        score+=5
    elif x[2]=="green":
        score+=1
    else:
        score-=5
    return score*-1

for i in range(20):
    print i
    guess = gp_minimize(my_input,my_output,dim3, search='lbfgs', n_restarts_optimizer=10)
    my_input.append(guess)
    my_output.append(BBfun(guess))
```
Regardless of whether the search is `lbfgs` or `sampling`, and with `n_restarts_optimizer` as high as 40, there are repeated inputs within 10 iterations.

**Comment by glouppe** [comment] 2016-07-28 20:13
Thanks for reporting the bug. Indeed we do not check whether the next point
to evaluate is already in the history.

While the problem is clear, the fix is not trivial, as it requires finding
the next optimum and so on. Though this could be checked easily when
search=sampling.

**Comment by ardunn** [comment] 2016-07-28 20:35
Ok, thank you. I am working on a primitive fix which randomly samples from the remaining discrete space. If you are interested in incorporating this feature I will submit a pull request.

**Comment by MechCoder** [comment] 2016-07-28 20:51
Is there a typo in your code snippet, in this line?

```python
guess = gp_minimize(my_input, my_output,dim, search='lbfgs', n_restarts_optimizer=10)
```

The first and second argument should be the func and the dimensions. Or did you modify gp_minimize interallly to have a warm-start like interface?

**Comment by MechCoder** [comment] 2016-07-28 20:53
Umm yeah it searches repeatedly over a few points. A hack might be to search over the remaining space. But I'll have to think over the problem a bit more closely.

**Comment by nfcampos** [comment] 2016-07-28 20:56
if we were absolutely sure the search method is behaving correctly then the fact that it suggests trying a point that was already tried before actually sounds like a stopping criterion ("the best point I can find to test next has already been tested"), no?

**Comment by ardunn** [comment] 2016-07-28 21:18
@MechCoder no, that is not a typo. Yes, you are correct I modified it, because I need direct control over every function evaluation and optimization run. I had to modify the actual file to execute the optimization loop in another script (ie using Skopt for only one optimization at a time)

For you guys, the fix can take place inside the optimization loop. When there is a repeat integer/category, you can calculate the entire space and then eliminate entries as you receive `next_x`. You then randomly sample from the remaining space, as @MechCoder suggested.

Calculating the entire discreet space of inputs could look something like this:
```
def calculate_discrete_space(dimensions):
        total_dimspace = []
        for dimension in dimensions:
            if type(dimension[0]) == int or type(dimension[0]) == np.int64:
                # Then the dimension is of the form (lower, upper)
                lower = dimension[0]
                upper = dimension[1]
                dimspace = list(range(lower, upper + 1))
            elif type(dimension[0]) == float or type(dimension[0]) == np.float64:
                # The chance of a random sample of identical float is nil
                raise ValueError("The dimension is a float. The dimension space is infinite.")
            else:  # The dimension is a discrete finite string list
                dimspace = dimension
            total_dimspace.append(dimspace)
        return list(itertools.product(*total_dimspace))
```
If all inputs to the function are either categorical or integer, you then see if `next_x in X`, and if so, remove `next_x` from the discrete space. Finally, random sample from this remaining (and shrinking) space until all possible combinations have been tried.

@nfcampos Yes that would be true, although unfortunately that is verifiably not the case.

**Comment by glouppe** [comment] 2016-07-29 05:00
Reopening as it is clearly something we should address. 

By the way, what is the acquisition function you are using? `acq="EI"` might fix it, as querying the same point again should yield an improvement of 0.

**Comment by MechCoder** [comment] 2016-07-29 05:01
It could also be because of the type of kernel used. I'll have a look right now.

**Comment by glouppe** [comment] 2016-07-29 05:04
> It could also be because of the type of kernel used. I'll have a look right now.

Yup, one thing to check is that the noise level is set to 0 (`alpha=0.0`). It is not by default.

**Comment by MechCoder** [comment] 2016-07-29 06:15
Yes, I'm unable to reproduce the repeated-values issue on master with acq set to EI

**Comment by ardunn** [comment] 2016-07-29 06:26
Is there a disadvantage to having the acq set to EI? As far as optimization efficiency per iteration goes

**Comment by glouppe** [comment] 2016-07-29 06:32
EI often works better than LCB (this is why EI is now the default acquisition function). LCB might get stucked in local minima, while it is less likely for EI. 

Also, I would recommend setting `search="sampling"` since `search="lbfgs"` might behave weirdly on discrete spaces like you have.

**Comment by MechCoder** [comment] 2016-07-29 15:50
We can close this?

**Comment by glouppe** [comment] 2016-07-29 15:52
Nope

**Comment by MechCoder** [comment] 2016-07-29 15:54
@ardunn Why not? Setting acq=EI does not fix it?

**Comment by betatim** [comment] 2016-07-29 16:09
I think we should at least add a warning when we detect that a sample is a repeat. It would be interesting to study a bit why this happens.

**Comment by ardunn** [comment] 2016-07-29 17:31
Setting acq=EI reduces the number of suboptimal repeats dramatically. But there are still times when the space has not nearly been explored fully and I am getting repeats.

**Comment by MechCoder** [comment] 2016-07-29 17:32
OK, I'll fix this up later today. Thanks for the report!

**Closed** 2017-01-13 09:32 UTC
Labels: Bug
