### ISSUE TITLE
Obtaining same functionality of gp_minimize with Optimizer

### ISSUE THREAD

**Issue by kittythecat** [scikit-optimize/scikit-optimize#402] opened 2017-06-15 15:19 UTC
gp_minimize works well for my problem set, but I'd really like to use the ask() and tell() features of Optimizer. However, I've been unable to reproduce gp_minimize using Optimizer. Is there an example that we can post somewhere?

Thank you

**Comment by betatim** [comment] 2017-06-15 16:10
Currently there is no example of how to reproduce the setup of any of the `*_minimize` functions.

There are two things to look at: how the space is transformed and how the kernel is setup. At the moment it is probably easiest to look at the [code](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/optimizer/gp.py#L206-L243).

Some related issues #338 #390 #400

**Comment by Young-Todd** [comment] 2017-06-23 03:08
@kittythecat, have you had any luck with this?

**Comment by MechCoder** [comment] 2017-06-23 03:48
#408 is a step in that direction.

**Comment by rene-rex** [comment] 2017-06-26 11:11
I am in the same situation as @kittythecat, so +1 from me!

**Comment by betatim** [comment] 2017-06-26 19:54
You should [now](https://github.com/scikit-optimize/scikit-optimize/pull/408) be able to now do something like:
```python
opt = Optimizer([(-2.0, 2.0)], "GP")
```
by providing a string as the optimizer you will get a surrogate model that is configured like the ones used in `*_minimize`. You can also look at `skopt.utils.cook_estimator()` to learn how they are configured.

**Comment by betatim** [comment] 2017-06-26 19:55
Feel free to keep discussing in this thread if this doesn't work (or open a new one if there is something not directly related to this).

Closing the issue to help us keep track of what needs doing for the v0.4 release.

**Comment by MechCoder** [comment] 2017-06-27 04:58
Hmm can we still keep this open?

It would be great to add a test to check that both indeed produce the same results.

**Comment by rene-rex** [comment] 2017-06-27 05:56
As far as I understand the code, `gp_minimize` is also doing some space transformations which are not handled by the new `cook_estimator` method. Should this be done by the user before constructing the optimizer? Maybe an option is to pull out the code from `gp_minimize` and offer a `skopt.utils.transform_space`?

**Comment by MechCoder** [comment] 2017-06-27 09:12
That's right. Would you like to propose a pull request?

**Comment by yngtodd** [comment] 2017-07-04 15:59
I have a short [notebook](https://github.com/yngtodd/skopt_notes/blob/master/optimizer_comparison.ipynb) that starts to look into how the `Optimizer` compares with `gp_minimize`. The notebook heavily borrows from Scikit-Optimize's [Bayesian optimization demo](https://scikit-optimize.github.io/notebooks/bayesian-optimization.html) and the [parallel optimization demo](https://scikit-optimize.github.io/notebooks/parallel-optimization.html). 

Seems like it would take a bit more work to get the `Optimizer` to match closely the behavior of `gp_minimize`. Following @rene-rex's point, the notebook takes the step to transform the dimensions for the `Optimizer` in the same way `gp_minimize` does (also used in https://github.com/scikit-optimize/scikit-optimize/pull/420).

 Any thoughts on where I could look further into to bring the results from `Optimizer` and `gp_minimize` closer together?

**Comment by betatim** [comment] 2017-07-06 05:46
> Any thoughts on where I could look further to bring the results from Optimizer and gp_minimize closer together?

Nice work! If you comment out the acquisition function choice you make when instantiating `Optimizer` you should get much closer results. I modified your notebook and uploaded it here: https://gist.github.com/betatim/faed0256d80547a45a33f8df70582f98

**Comment by Deepblue129** [comment] 2017-07-23 22:02
@yngtodd @betatim Hi! Is the above notebook the recommended way of accomplishing, "Obtaining same functionality of gp_minimize with Optimizer"?

Anything left to do?

**Comment by betatim** [comment] 2017-07-24 05:40
We think that you should be able to get the same behaviour out of the box with `master` now. If you could give it a try with your problem that would be great because I bet there are still bugs to be found :)

**Comment by glouppe** [comment] 2017-08-03 11:14
Is this still an issue or is a test just missing? We should fix it for 0.4 in any case.

**Comment by betatim** [comment] 2017-08-03 13:26
I'll add a test and then we will know.

**Closed** 2017-08-19 16:07 UTC
Labels: API
