### ISSUE TITLE
plot_evaluations throws "ValueError: too many values to unpack (expected 2)"

### ISSUE THREAD

**Issue by davenovelli** [scikit-optimize/scikit-optimize#395] opened 2017-06-08 17:50 UTC
I'm totally new to skopt so I may just be missing something, but the docs at (https://scikit-optimize.github.io/notebooks/visualizing-results.html) made it appear as though I can simply take the successful result of my forest_minimizer() call and pass that to plot_evaluations(). There are a total of 5 parameters I'm testing. One of them was categorical which I converted into 0/1 but the result is the same:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-71-7b778aaceb58> in <module>()
      2 from skopt.plots import plot_evaluations
      3 print(res_fm)
----> 4 _ = plot_evaluations(res_fm)

/Users/davenovelli/miniconda3/envs/strvworkshop/lib/python3.5/site-packages/skopt/plots.py in plot_evaluations(result, bins)
    368             if i == j:
    369                 ax[i, i].hist(samples[:, j], bins=bins,
--> 370                               range=space.dimensions[j].bounds)
    371 
    372             # lower triangle

/Users/davenovelli/miniconda3/envs/strvworkshop/lib/python3.5/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1896                     warnings.warn(msg % (label_namer, func.__name__),
   1897                                   RuntimeWarning, stacklevel=2)
-> 1898             return func(ax, *args, **kwargs)
   1899         pre_doc = inner.__doc__
   1900         if pre_doc is None:

/Users/davenovelli/miniconda3/envs/strvworkshop/lib/python3.5/site-packages/matplotlib/axes/_axes.py in hist(***failed resolving arguments***)
   6193             # this will automatically overwrite bins,
   6194             # so that each histogram uses the same bins
-> 6195             m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
   6196             m = m.astype(float)  # causes problems later if it's an int
   6197             if mlast is None:

/Users/davenovelli/miniconda3/envs/strvworkshop/lib/python3.5/site-packages/numpy/lib/function_base.py in histogram(a, bins, range, normed, weights, density)
    661             mn, mx = a.min() + 0.0, a.max() + 0.0
    662     else:
--> 663         mn, mx = [mi + 0.0 for mi in range]
    664     if mn > mx:
    665         raise ValueError(

ValueError: too many values to unpack (expected 2)
```

**Comment by davenovelli** [comment] 2017-06-08 19:26
This was a basic misunderstanding of how the space array is handled and how skopt works. My space originally looked like this:

```
space = [(5, 10, 25, 50, 100),      # epochs
         ('adagrad', 'adadelta'),   # learning_rate_schedule
         (0.005, 0.01, 0.05, 0.1),  # initial learning rate for adagrad
         (5, 10, 25, 50, 100),      # no_components
         (5, 10, 25)                # max_sampled
        ]
```

Which obviously I missed the part where any parameter with more than 3 values is by definition a categorical, and otherwise values are sampled from the range specified in the tuple. So, this following parameter space worked and I was able to generate the plot of evaluations:

```
space = [(5, 100),     # epochs
         (0, 1),       # learning_rate_schedule
         (0.005, 0.1), # initial learning rate for adagrad
         (5, 100),     # no_components
         (5, 25)       # max_sampled
        ]
```

**Comment by glouppe** [comment] 2017-06-08 19:59
Thanks for the report Dave! Closing this then.

**Closed by glouppe** 2017-06-08 19:59 UTC

**Comment by betatim** [comment] 2017-06-09 05:25
We could provide a better error message in the plot functions, I think the problem is that categorical dimensions are not supported in the plotting functions.

**Comment by bionicles** [comment] 2019-07-01 19:49
this is pretty prohibitive because we need to represent names with integers which can cause confusion and force us to repeat ourselves if we want different hyperparameters to share names

for example in neural network we might use similar layer type names for 2 hyperparameters. it's hard to know what a "1" is, but it's easy to know what a "dense" is
