### ISSUE TITLE
gp_example len() of unsized object

### ISSUE THREAD

**Issue by kegl** [scikit-optimize/scikit-optimize#135] opened 2016-07-21 16:29 UTC
This

scikit-optimize/examples/plot_gp_minimize_1d.py

throws an error:

Traceback (most recent call last):
  File "gp_example.py", line 57, in <module>
    plt.fill_between(x, -1.5, acquis_values, alpha=0.3, color='green', label="LCB values")
  File "/Users/kegl/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2826, in fill_between
    interpolate=interpolate, **kwargs)
  File "/Users/kegl/anaconda/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 4340, in fill_between
    where = np.ones(len(x), np.bool)
TypeError: len() of unsized object

**Comment by betatim** [comment] 2016-07-21 17:29
Related to #122

**Comment by betatim** [comment] 2016-07-21 17:45
What does `git log -1` say? I can't reproduce this locally.

The traceback mentions `gp_example.py` which isn't one of our examples??

**Comment by MechCoder** [comment] 2016-07-21 17:57
python2.7 issues?

**Comment by betatim** [comment] 2016-07-21 18:03
If it is, we should fix it. (I think we now more or less officially support legacy python.) Let's keep it open till we hear back from @kegl.

**Comment by glouppe** [comment] 2016-07-27 10:51
Closing, those scripts have been removed. For examples, see the notebooks.

**Closed by glouppe** 2016-07-27 10:51 UTC
Labels: Bug, Easy
