### ISSUE TITLE
Runaway memory use?

### ISSUE THREAD

**Issue by dhirschfeld** [scikit-optimize/scikit-optimize#349] opened 2017-04-10 21:20 UTC
I'm using `gm_minimize` for feature selection in a GBRT model. There are ~150 possible features and I'm looking for the best 20 which will give the most predictive model. My objective function thus trains a GBRT model and returns the cross-val score.

What I'm observing is that memory use goes up and down periodically , but the amplitude of the "waves" gradually increases. At the start of the optimization the memory peaked at ~35GB. After many hours and 100 iterations (of each of the 3 optimizations I'm running in parallel) the memory usage now peaks at >112GB and unsurprisingly the time for each iteration has more than doubled.

Is this expected behaviour? i.e. should the memory requirements for each iteration step continuously increase as the optimization progresses?

**Comment by dhirschfeld** [comment] 2017-04-10 21:24
![image](https://cloud.githubusercontent.com/assets/881019/24883340/ce1915b0-1e87-11e7-9745-1fb6152461ee.png)

**Comment by betatim** [comment] 2017-04-11 07:27
The quick answer is: yes. We store each fitted surrogate model created during each iteration, so memory use will keep going up.

To find out if this is indeed the cause (or if there is a leak) you could make a quick hack that only stores the last model and see what happens if you run it with an objective function that is fast to evaluate.

We should consider offering an option to store only the last N models/only ever Nth model for people who do not need to/want to inspect each surrogate in detail.

**Comment by dhirschfeld** [comment] 2017-04-11 07:58
...maybe also a spill-to-disk cache for the model history.

**Comment by dhirschfeld** [comment] 2017-04-11 08:05
Just for reference, I'm assuming you're talking about [this](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/optimizer/optimizer.py#L272) line.

**Comment by Bacoknight** [comment] 2019-02-06 21:46
Bit of a necropost, but I've noticed a similar issue for my optimisations too, which are run for many iterations. Has anyone managed to find a proper way around this? I don't need to keep previous models as I only care for the result (for now). I can't seem to find how to discard older models.

**Comment by glouppe** [comment] 2020-01-17 11:05
Fixed by #746

**Closed by glouppe** 2020-01-17 11:05 UTC
